# Copyright (c) 2023-2024, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from typing import Any, Iterable, List, overload

import cudf
import polars as pl
import pyarrow as pa
from legate.core import StoreTarget

from legate_dataframe.lib.core.column import LogicalColumn

class LogicalTable:
    def __init__(
        self, columns: Iterable[LogicalColumn], column_names: Iterable[str]
    ) -> None: ...
    @staticmethod
    def from_cudf(df: cudf.DataFrame) -> LogicalTable: ...
    @staticmethod
    def from_arrow(table: pa.Table) -> LogicalTable: ...
    def lazy(self) -> pl.LazyFrame: ...
    def num_columns(self) -> int: ...
    def num_rows(self) -> int: ...
    def get_column(self, column: int | str) -> LogicalColumn: ...
    def select(self, columns: Iterable[str] | Iterable[int]) -> LogicalTable: ...
    @overload
    def __getitem__(self, column: int | str) -> LogicalColumn: ...
    @overload
    def __getitem__(self, column: List[int] | List[str]) -> LogicalTable: ...
    def get_column_names(self) -> list[str]: ...
    def to_array(self, *, out: Any) -> Any: ...
    def to_arrow(self) -> pa.Table: ...
    def to_cudf(self) -> cudf.DataFrame: ...
    def offload_to(target_mem: StoreTarget) -> None: ...
    def slice(self, slice_) -> LogicalTable: ...
    def repr(self, max_num_items: int) -> str: ...
    def __repr__(self) -> str: ...
